---
elasticsearch_curator_cron_jobs:
  - {
    name: "Delete old elasticsearch indices.",
    job: "/usr/local/bin/curator delete indices --older-than 30 --time-unit days --timestring '\\%Y.\\%m.\\%d'",
    minute: 0,
    hour: 1
  }
  - {
    name: "Close old elasticsearch indices.",
    job: "/usr/local/bin/curator close indices --older-than 14 --time-unit days --timestring '\\%Y.\\%m.\\%d'",
    minute: 30,
    hour: 1
  }
