---
- hosts: all
  tasks:
   - name: "安装 Apache"
     command: yum install --quiet -y httpd httpd-devel
   - name: "复制配置文件"
     command: cp /tmp/httpd.conf /etc/httpd/conf/httpd.conf
     command: cp /tmp/httpd-vhosts.conf /etc/httpd/conf/httpd-vhosts.conf
   - name: "检查Apache运行状态，并设置开机启动"
     command: service httpd start
     command: chkconfig httpd on

